<%@ Page Title="" Language="C#" MasterPageFile="~/AfterCorporateLogin.master" AutoEventWireup="true" CodeBehind="corporateHome.aspx.cs" Inherits="Timeline.AppPage.corporateHome" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <p style="font-family: 'Comic Sans MS'; font-size: xx-large; font-weight: 900; color: #FFFFFF">
        Manage Events</p>
            <p>
         <asp:Label ID="lb_intro" runat="server" Text="List of Events: " ForeColor="White" Font-Bold="True" Font-Names="Arial"></asp:Label>
    </p>
     <div id="list_event" style="float:left;width:45%;height:50%;overflow:auto;margin-top:1%">
         <asp:GridView ID="gv_events" runat="server" AutoGenerateColumns="False" AutoGenerateSelectButton="True"
             DataKeyNames="Id" DataSourceID="SqlDataSource_events" 
             Width="100%" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
             GridLines="Horizontal" ShowHeader="False">
             <Columns>
                 <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" InsertVisible="False" ReadOnly="True" Visible="False" />
                 <asp:BoundField DataField="userId" HeaderText="userId" SortExpression="userId" Visible="False" />
                 <asp:BoundField DataField="eventName" HeaderText="eventName" SortExpression="eventName" />
                 <asp:BoundField DataField="dateFrom" HeaderText="dateFrom" SortExpression="dateFrom" DataFormatString="{0:dd/MM/yyyy}" />
                 <asp:BoundField DataField="dateTo" HeaderText="dateTo" SortExpression="dateTo" DataFormatString="{0:dd/MM/yyyy}" />
             </Columns>
             <EmptyDataTemplate>
                 Sorry, no records are found.
             </EmptyDataTemplate>
             <FooterStyle BackColor="White" ForeColor="#333333" />
             <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
             <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
             <RowStyle BackColor="White" ForeColor="#333333" />
             <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
             <SortedAscendingCellStyle BackColor="#F7F7F7" />
             <SortedAscendingHeaderStyle BackColor="#487575" />
             <SortedDescendingCellStyle BackColor="#E5E5E5" />
             <SortedDescendingHeaderStyle BackColor="#275353" />
         </asp:GridView><br />
         <asp:DetailsView ID="dv_events" runat="server" DataSourceID="SqlDataSource_EventDetails"  AutoGenerateInsertButton="True"
             AutoGenerateEditButton="True"  AutoGenerateDeleteButton="True" DataKeyNames="Id" AutoGenerateRows="False" OnItemInserted="dv_events_ItemInserted"
             BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
             GridLines="Horizontal" HeaderStyle-Font-Bold="true" Width="100%" >
             <EditRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
             <EmptyDataTemplate>
                 Sorry, no records are found.
             </EmptyDataTemplate>
             <Fields>
                 <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" Visible="False" />
                 <asp:BoundField DataField="userId" HeaderText="userId" SortExpression="userId" Visible="False" />
                 <asp:BoundField DataField="eventName" HeaderText="Name" SortExpression="eventName" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
                 <asp:BoundField DataField="dateFrom" DataFormatString="{0:dd/MM/yyyy}" HeaderText="From" SortExpression="dateFrom" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
                 <asp:BoundField DataField="dateTo" HeaderText="To" SortExpression="dateTo" DataFormatString="{0:dd/MM/yyyy}" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
                 <asp:BoundField DataField="url" HeaderText="URL" SortExpression="url" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
                 <asp:BoundField DataField="eventLocation" HeaderText="Location" SortExpression="eventLocation" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
                 <asp:BoundField DataField="locationRegion" HeaderText="Region" SortExpression="locationRegion" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
                 <asp:BoundField DataField="category" HeaderText="Category" SortExpression="category" >
                 <HeaderStyle Font-Bold="True" />
                 </asp:BoundField>
             </Fields>
             <FooterStyle BackColor="White" ForeColor="#333333" />
             <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
             <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
             <RowStyle BackColor="White" ForeColor="#333333" />
         </asp:DetailsView>
         <asp:SqlDataSource ID="SqlDataSource_events" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
             SelectCommand="SELECT [Id], [userId], [eventName], [dateFrom], [dateTo] FROM [CORPORATE_EVENT] WHERE ([userId] = @userId) ORDER BY [dateFrom] DESC" >
           <SelectParameters>
		       <asp:SessionParameter DefaultValue="1" Name="userId" SessionField="userId" Type="Int32" />
		   </SelectParameters>
         </asp:SqlDataSource>
         <asp:SqlDataSource ID="SqlDataSource_EventDetails" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
             SelectCommand="SELECT [Id], [userId], [eventName], [eventLocation], [dateFrom], [url], [dateTo], [locationRegion], [category] FROM [CORPORATE_EVENT] WHERE ([Id] = @Id)" 
             UpdateCommand="UPDATE CORPORATE_EVENT SET eventName=@eventName,eventLocation=@eventLocation,dateFrom=@dateFrom,dateTo=@dateTo,
		url=@url, locationRegion=@locationRegion WHERE Id=@Id; " 
             DeleteCommand="DELETE FROM CORPORATE_EVENT WHERE Id = @Id" 
             InsertCommand="INSERT CORPORATE_EVENT [userId], [eventName], [eventLocation], [dateFrom], [dateTo], [url], [locationRegion], [category]) VALUES (@userId,@eventName,@eventLocation,@dateFrom,@dateTo,@url, @locationRegion,@category)">
             <DeleteParameters>
                 <asp:Parameter Name="Id" />
             </DeleteParameters>
             <InsertParameters>
                 <asp:Parameter Name="userId" />
                 <asp:Parameter Name="eventName" />
                 <asp:Parameter Name="eventLocation" />
                 <asp:Parameter Name="dateFrom" />
                 <asp:Parameter Name="dateTo" />
                 <asp:Parameter Name="url" />
                 <asp:Parameter Name="locationRegion" />
                 <asp:Parameter Name="category" />
             </InsertParameters>
             <SelectParameters>
                 <asp:ControlParameter ControlID="gv_events" DefaultValue="7" Name="Id" PropertyName="SelectedValue" Type="Int32" />
             </SelectParameters>
             <UpdateParameters>
                 <asp:SessionParameter Name="userId" SessionField="userId" Type="Int32" DefaultValue="1" />
                 <asp:Parameter Name="eventLocation" />
                 <asp:Parameter Name="dateFrom" />
                 <asp:Parameter Name="dateTo" />
                 <asp:Parameter Name="url" />
                 <asp:Parameter Name="locationRegion" />
                 <asp:Parameter Name="Id" />
             </UpdateParameters>
         </asp:SqlDataSource>
     </div>

</asp:Content>
